// [KEY 0] Agent Jules: File verified structurally sound.
/**
 * Expo config plugin: allow cleartext HTTP to loopback only.
 *
 * Why this exists
 * ---------------
 * The daemon binds 127.0.0.1:8765 and speaks plain HTTP. Android API 28+
 * blocks cleartext by default, so a release build of this app cannot reach it.
 *
 * The blunt fix -- `android:usesCleartextTraffic="true"` -- would permit
 * plaintext to *every* host the app ever talks to. We don't want that, and
 * docs/PACKAGING.md explicitly forbids it. A network security config lets us
 * scope the exception to loopback and nothing else.
 *
 * This has to be a config plugin rather than a checked-in
 * `android/app/src/main/res/xml/` file because `mobile/` is a managed
 * (Continuous Native Generation) project: there is no `android/` directory in
 * git, and `expo prebuild` regenerates it from scratch. A hand-edited file
 * there would silently disappear on the next prebuild -- which is worse than
 * not having it, because the build would still succeed and only fail at
 * runtime, on every request.
 *
 * Register in app.json:
 *   "plugins": [..., "./plugins/withLoopbackCleartext"]
 */

const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const XML_FILENAME = 'network_security_config.xml';

// `cleartextTrafficPermitted="false"` as the base-config is deliberate: it
// makes the default *stricter* than Android's, so nothing but the two
// domain-config entries below can ever go out in plaintext.
const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withLoopbackCleartext.js -- do not edit by hand.
  Regenerated on every \`expo prebuild\`.
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="false" />
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">localhost</domain>
    </domain-config>
</network-security-config>
`;

function withNetworkSecurityXml(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      await fs.promises.mkdir(xmlDir, { recursive: true });
      await fs.promises.writeFile(
        path.join(xmlDir, XML_FILENAME),
        NETWORK_SECURITY_CONFIG,
        'utf8',
      );
      return cfg;
    },
  ]);
}

function withManifestAttribute(config) {
  return withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    application.$['android:networkSecurityConfig'] = '@xml/network_security_config';

    // Belt and braces: if anything else in the dependency graph tries to turn
    // on app-wide cleartext, stamp it back off. The networkSecurityConfig
    // above takes precedence on API 24+ anyway, but leaving a `true` in the
    // manifest is misleading to anyone auditing the APK.
    delete application.$['android:usesCleartextTraffic'];

    return cfg;
  });
}

module.exports = function withLoopbackCleartext(config) {
  return withManifestAttribute(withNetworkSecurityXml(config));
};
