// DO NOT change the contents or parameters of the vitest suite without expressed, written, human permission. if a UI-rendering vitest fails, we will know with certainty.
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import SubtitlesDrawer from '../components/SubtitlesDrawer';
import * as daemonLib from '../lib/daemon';
import { vi, describe, it, expect, beforeEach } from 'vitest';

vi.mock('../lib/daemon', () => ({
  daemon: {
    getAvailableSubtitles: vi.fn(),
    selectSubtitle: vi.fn(),
    listRemoteSubtitles: vi.fn(),
    fetchRemoteSubtitle: vi.fn(),
  }
}));

describe('SubtitlesDrawer', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renders available local tracks and handles track selection', async () => {
    vi.mocked(daemonLib.daemon.getAvailableSubtitles).mockResolvedValue({
      source_type: 'local',
      active_track_ids: [1],
      tracks: [
        { track_id: 1, language: 'eng', label: 'English [Embedded]', source: 'embedded' },
        { track_id: 2, language: 'spa', label: 'Spanish [Sidecar]', source: 'sidecar' }
      ],
      remote_supported: true
    });

    render(<SubtitlesDrawer isOpen={true} onClose={vi.fn()} sourceType="local" />);

    await waitFor(() => {
      expect(screen.getByText('English [Embedded]')).toBeInTheDocument();
      expect(screen.getByText('Spanish [Sidecar]')).toBeInTheDocument();
    });

    // Select Spanish
    fireEvent.click(screen.getByText('Spanish [Sidecar]'));
    await waitFor(() => {
      expect(daemonLib.daemon.selectSubtitle).toHaveBeenCalledWith(2);
    });

    // Disable subtitles
    fireEvent.click(screen.getByRole('button', { name: /turn subtitles off/i }));
    await waitFor(() => {
      expect(daemonLib.daemon.selectSubtitle).toHaveBeenCalledWith(null);
    });
  });

  it('renders header source badge correctly for Amazon 4K, YouTube, and Local Media', async () => {
    vi.mocked(daemonLib.daemon.getAvailableSubtitles).mockResolvedValue({
      source_type: 'amazon',
      active_track_ids: [],
      tracks: [],
      remote_supported: false
    });

    const { rerender } = render(<SubtitlesDrawer isOpen={true} onClose={vi.fn()} sourceType="amazon" />);
    await waitFor(() => {
      expect(screen.getByText('Amazon 4K')).toBeInTheDocument();
    });

    vi.mocked(daemonLib.daemon.getAvailableSubtitles).mockResolvedValue({
      source_type: 'youtube',
      active_track_ids: [],
      tracks: [],
      remote_supported: true
    });
    rerender(<SubtitlesDrawer isOpen={true} onClose={vi.fn()} sourceType="youtube" />);
    await waitFor(() => {
      expect(screen.getByText('YouTube')).toBeInTheDocument();
    });
  });

  it('renders categorized remote tabs for YouTube and handles remote fetch', async () => {
    vi.mocked(daemonLib.daemon.getAvailableSubtitles).mockResolvedValue({
      source_type: 'youtube',
      active_track_ids: [],
      tracks: [],
      remote_supported: true
    });

    vi.mocked(daemonLib.daemon.listRemoteSubtitles).mockResolvedValue([
      { language: 'eng', language_name: 'English', label: 'English', type: 'manual', url: 'https://yt.com/en.vtt' },
      { language: 'eng', language_name: 'English', label: 'English (autogenerated)', type: 'autogenerated', url: 'https://yt.com/en-auto.vtt' },
      { language: 'spa', language_name: 'Spanish', label: 'Spanish (translated)', type: 'translated', url: 'https://yt.com/es-trans.vtt' }
    ]);

    vi.mocked(daemonLib.daemon.fetchRemoteSubtitle).mockResolvedValue(undefined as any);

    render(<SubtitlesDrawer isOpen={true} onClose={vi.fn()} sourceType="youtube" />);

    await waitFor(() => {
      expect(daemonLib.daemon.listRemoteSubtitles).toHaveBeenCalled();
    });

    // Verify categorized tab buttons exist
    await waitFor(() => {
      expect(screen.getByRole('button', { name: /creator \/ manual/i })).toBeInTheDocument();
      expect(screen.getByRole('button', { name: /\(autogenerated\)/i })).toBeInTheDocument();
      expect(screen.getByRole('button', { name: /\(translated\)/i })).toBeInTheDocument();
    });

    // In Creator / Manual tab, English should be visible
    expect(screen.getByText('English')).toBeInTheDocument();

    // Click to fetch English manual subtitle
    fireEvent.click(screen.getByText('English'));
    await waitFor(() => {
      expect(daemonLib.daemon.fetchRemoteSubtitle).toHaveBeenCalledWith({
        language: 'eng',
        type: 'manual',
        url: 'https://yt.com/en.vtt'
      });
    });

    // Switch to autogenerated tab
    fireEvent.click(screen.getByRole('button', { name: /\(autogenerated\)/i }));
    await waitFor(() => {
      expect(screen.getByText('English (autogenerated)')).toBeInTheDocument();
    });
  });

  it('renders remote search for local media and fetches remote subtitle', async () => {
    vi.mocked(daemonLib.daemon.getAvailableSubtitles).mockResolvedValue({
      source_type: 'local',
      active_track_ids: [],
      tracks: [],
      remote_supported: true
    });

    vi.mocked(daemonLib.daemon.listRemoteSubtitles).mockResolvedValue([
      { language: 'eng', language_name: 'English', label: 'English (BluRay)', type: 'manual', url: 'https://subdl.com/sub.zip' }
    ]);
    vi.mocked(daemonLib.daemon.fetchRemoteSubtitle).mockResolvedValue(undefined as any);

    render(<SubtitlesDrawer isOpen={true} onClose={vi.fn()} sourceType="local" />);

    await waitFor(() => {
      expect(screen.getByPlaceholderText(/search subtitles/i)).toBeInTheDocument();
    });

    const searchInput = screen.getByPlaceholderText(/search subtitles/i);
    fireEvent.change(searchInput, { target: { value: 'Inception' } });

    const searchButton = screen.getByRole('button', { name: /^search$/i });
    fireEvent.click(searchButton);

    await waitFor(() => {
      expect(daemonLib.daemon.listRemoteSubtitles).toHaveBeenCalledWith({ query: 'Inception', language: '' });
      expect(screen.getByText('English (BluRay)')).toBeInTheDocument();
    });

    fireEvent.click(screen.getByText('English (BluRay)'));
    await waitFor(() => {
      expect(daemonLib.daemon.fetchRemoteSubtitle).toHaveBeenCalledWith({
        language: 'eng',
        type: 'manual',
        url: 'https://subdl.com/sub.zip'
      });
    });
  });

  it('calls onClose when close button or backdrop is clicked', async () => {
    vi.mocked(daemonLib.daemon.getAvailableSubtitles).mockResolvedValue({
      source_type: 'local',
      active_track_ids: [],
      tracks: [],
      remote_supported: false
    });

    const onClose = vi.fn();
    render(<SubtitlesDrawer isOpen={true} onClose={onClose} sourceType="local" />);

    await waitFor(() => {
      expect(screen.getByRole('button', { name: /turn subtitles off/i })).toBeInTheDocument();
    });

    const closeBtn = screen.getByRole('button', { name: /close subtitles drawer/i });
    fireEvent.click(closeBtn);
    expect(onClose).toHaveBeenCalledTimes(1);

    const backdrop = screen.getByTestId('subtitles-drawer-backdrop');
    fireEvent.click(backdrop);
    expect(onClose).toHaveBeenCalledTimes(2);
  });

  it('passes language input to listRemoteSubtitles when searching external subtitles', async () => {
    vi.mocked(daemonLib.daemon.getAvailableSubtitles).mockResolvedValue({
      source_type: 'local',
      active_track_ids: [],
      tracks: [],
      remote_supported: true
    });

    vi.mocked(daemonLib.daemon.listRemoteSubtitles).mockResolvedValue([]);

    render(<SubtitlesDrawer isOpen={true} onClose={vi.fn()} sourceType="local" />);

    await waitFor(() => {
      expect(screen.getByPlaceholderText(/search subtitles/i)).toBeInTheDocument();
      expect(screen.getByPlaceholderText(/language/i)).toBeInTheDocument();
    });

    const queryInput = screen.getByPlaceholderText(/search subtitles/i);
    const langInput = screen.getByPlaceholderText(/language/i);

    fireEvent.change(queryInput, { target: { value: 'The Matrix' } });
    fireEvent.change(langInput, { target: { value: 'spa' } });

    const searchButton = screen.getByRole('button', { name: /^search$/i });
    fireEvent.click(searchButton);

    await waitFor(() => {
      expect(daemonLib.daemon.listRemoteSubtitles).toHaveBeenCalledWith({
        query: 'The Matrix',
        language: 'spa'
      });
    });
  });

  it('dismisses drawer when Escape key is pressed', async () => {
    vi.mocked(daemonLib.daemon.getAvailableSubtitles).mockResolvedValue({
      source_type: 'local',
      active_track_ids: [],
      tracks: [],
      remote_supported: false
    });

    const onClose = vi.fn();
    render(<SubtitlesDrawer isOpen={true} onClose={onClose} sourceType="local" />);

    await waitFor(() => {
      expect(screen.getByRole('button', { name: /turn subtitles off/i })).toBeInTheDocument();
    });

    fireEvent.keyDown(window, { key: 'Escape', code: 'Escape' });
    expect(onClose).toHaveBeenCalledTimes(1);
  });

  it('resets error on handleSelectTrack and handleTurnOff', async () => {
    vi.mocked(daemonLib.daemon.getAvailableSubtitles).mockResolvedValue({
      source_type: 'local',
      active_track_ids: [1],
      tracks: [{ track_id: 1, language: 'eng', label: 'English', source: 'embedded' }],
      remote_supported: false
    });

    render(<SubtitlesDrawer isOpen={true} onClose={vi.fn()} sourceType="local" />);

    await waitFor(() => {
      expect(screen.getByText('English')).toBeInTheDocument();
    });

    // Simulate an error occurring first on selection failure
    vi.mocked(daemonLib.daemon.selectSubtitle).mockRejectedValueOnce(new Error('Switch failed'));
    fireEvent.click(screen.getByText('English'));

    await waitFor(() => {
      expect(screen.getByText('Switch failed')).toBeInTheDocument();
    });

    // Next action (e.g. handleTurnOff) should clear previous error
    vi.mocked(daemonLib.daemon.selectSubtitle).mockResolvedValue(undefined as any);
    fireEvent.click(screen.getByRole('button', { name: /turn subtitles off/i }));

    await waitFor(() => {
      expect(screen.queryByText('Switch failed')).not.toBeInTheDocument();
    });
  });
});
