import React, { useEffect, useState, useCallback } from "react";
import { X, Check, Loader2, Subtitles, EyeOff, Search, Globe, AlertCircle } from "lucide-react";
import { daemon, SubtitleTrack, SubtitlesResponse, RemoteSubtitle } from "../lib/daemon";

export interface SubtitlesDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  sourceType?: string | null;
  activeTrackIds?: number[];
  onSubtitlesChanged?: (activeTrackIds: number[]) => void;
}

export const SubtitlesDrawer: React.FC<SubtitlesDrawerProps> = ({
  isOpen,
  onClose,
  sourceType,
  activeTrackIds: propActiveTrackIds,
  onSubtitlesChanged,
}) => {
  const [subtitlesData, setSubtitlesData] = useState<SubtitlesResponse | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [activeTrackIds, setActiveTrackIds] = useState<number[]>(propActiveTrackIds || []);

  // Remote subtitles state
  const [remoteSubtitles, setRemoteSubtitles] = useState<RemoteSubtitle[]>([]);
  const [loadingRemote, setLoadingRemote] = useState<boolean>(false);
  const [remoteError, setRemoteError] = useState<string | null>(null);
  const [fetchingUrl, setFetchingUrl] = useState<string | null>(null);

  // YouTube tab selection
  const [youtubeTab, setYoutubeTab] = useState<"manual" | "autogenerated" | "translated">("manual");

  // Local search state
  const [searchQuery, setSearchQuery] = useState<string>("");
  const [searchLang, setSearchLang] = useState<string>("");

  const fetchAvailableSubtitles = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await daemon.getAvailableSubtitles();
      setSubtitlesData(data);
      if (data.active_track_ids !== undefined) {
        setActiveTrackIds(data.active_track_ids);
      }
      return data;
    } catch (err: any) {
      setError(err?.message || "Failed to load subtitle tracks");
      return null;
    } finally {
      setLoading(false);
    }
  }, []);

  const loadRemoteSubtitles = useCallback(async (query = "", language = "") => {
    setLoadingRemote(true);
    setRemoteError(null);
    try {
      const results = await daemon.listRemoteSubtitles({ query, language });
      setRemoteSubtitles(results || []);
    } catch (err: any) {
      setRemoteError(err?.message || "Failed to fetch remote subtitles");
      setRemoteSubtitles([]);
    } finally {
      setLoadingRemote(false);
    }
  }, []);

  useEffect(() => {
    if (!isOpen) {
      setRemoteSubtitles([]);
      setRemoteError(null);
      setError(null);
      return;
    }

    fetchAvailableSubtitles().then((data) => {
      const effectiveSource = (data?.source_type || sourceType || "local").toLowerCase();
      if (data?.remote_supported && effectiveSource.includes("youtube")) {
        loadRemoteSubtitles();
      }
    });
  }, [isOpen, sourceType, fetchAvailableSubtitles, loadRemoteSubtitles]);

  useEffect(() => {
    if (propActiveTrackIds !== undefined) {
      setActiveTrackIds(propActiveTrackIds);
    }
  }, [propActiveTrackIds]);

  if (!isOpen) return null;

  const effectiveSource = (subtitlesData?.source_type || sourceType || "local").toLowerCase();
  const isYouTube = effectiveSource.includes("youtube");
  const isAmazon = effectiveSource.includes("amazon");
  const isLocal = effectiveSource.includes("local");

  const getSourceBadge = () => {
    if (isAmazon) {
      return {
        label: "Amazon 4K",
        classes: "border-amber-500/40 bg-amber-500/10 text-amber-300",
      };
    }
    if (isYouTube) {
      return {
        label: "YouTube",
        classes: "border-red-500/40 bg-red-500/10 text-red-300",
      };
    }
    return {
      label: "Local Media",
      classes: "border-emerald-500/40 bg-emerald-500/10 text-emerald-300",
    };
  };

  const badge = getSourceBadge();

  const handleSelectTrack = async (trackId: number) => {
    try {
      await daemon.selectSubtitle(trackId);
      const newIds = [trackId];
      setActiveTrackIds(newIds);
      onSubtitlesChanged?.(newIds);
    } catch (err: any) {
      setError(err?.message || "Failed to switch subtitle track");
    }
  };

  const handleTurnOff = async () => {
    try {
      await daemon.selectSubtitle(null);
      setActiveTrackIds([]);
      onSubtitlesChanged?.([]);
    } catch (err: any) {
      setError(err?.message || "Failed to turn subtitles off");
    }
  };

  const handleFetchRemote = async (track: RemoteSubtitle) => {
    setFetchingUrl(track.url);
    setRemoteError(null);
    try {
      await daemon.fetchRemoteSubtitle({
        language: track.language,
        type: track.type,
        url: track.url,
      });
      // Refresh available tracks to get the new track and active state
      const refreshed = await daemon.getAvailableSubtitles();
      setSubtitlesData(refreshed);
      if (refreshed.active_track_ids !== undefined) {
        setActiveTrackIds(refreshed.active_track_ids);
        onSubtitlesChanged?.(refreshed.active_track_ids);
      }
    } catch (err: any) {
      setRemoteError(err?.message || "Failed to download subtitle");
    } finally {
      setFetchingUrl(null);
    }
  };

  const handleLocalSearch = (e: React.FormEvent) => {
    e.preventDefault();
    loadRemoteSubtitles(searchQuery, searchLang);
  };

  const tracks = subtitlesData?.tracks || [];
  const remoteSupported = subtitlesData?.remote_supported ?? false;

  const youtubeTracksForTab = remoteSubtitles.filter((t) => t.type === youtubeTab);

  return (
    <div className="fixed inset-0 z-50 overflow-hidden font-sans">
      {/* Backdrop */}
      <div
        data-testid="subtitles-drawer-backdrop"
        className="fixed inset-0 bg-black/70 backdrop-blur-sm transition-opacity"
        onClick={onClose}
      />

      {/* Slide-over panel */}
      <div
        role="dialog"
        aria-modal="true"
        aria-label="Subtitles Drawer"
        className="fixed inset-y-0 right-0 flex w-full max-w-md flex-col bg-[#070b09] border-l border-emerald-500/30 text-emerald-300 shadow-2xl z-50 overflow-hidden"
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-emerald-500/20 px-5 py-4 bg-[#0a100d]">
          <div className="flex items-center gap-3">
            <Subtitles className="h-5 w-5 text-emerald-400" />
            <h2 className="text-base font-semibold tracking-wide text-emerald-100 uppercase">Subtitles</h2>
            <span className={`rounded border px-2 py-0.5 text-xs font-mono font-medium ${badge.classes}`}>
              {badge.label}
            </span>
          </div>
          <button
            onClick={onClose}
            aria-label="Close subtitles drawer"
            className="rounded p-1.5 text-emerald-400/80 hover:bg-emerald-500/20 hover:text-emerald-200 transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content area */}
        <div className="flex-1 overflow-y-auto px-5 py-4 space-y-6">
          {/* Main Error */}
          {error && (
            <div className="flex items-center gap-2 rounded border border-red-500/40 bg-red-500/10 p-3 text-sm text-red-300">
              <AlertCircle className="h-4 w-4 shrink-0 text-red-400" />
              <span>{error}</span>
            </div>
          )}

          {/* Turn Subtitles Off */}
          <div>
            <button
              type="button"
              onClick={handleTurnOff}
              className={`flex w-full items-center justify-center gap-2 rounded border py-2.5 text-sm font-medium transition-all ${
                activeTrackIds.length === 0
                  ? "border-emerald-500/50 bg-emerald-500/20 text-emerald-100 shadow-sm"
                  : "border-emerald-500/25 bg-emerald-500/5 text-emerald-400 hover:bg-emerald-500/15 hover:border-emerald-500/40"
              }`}
            >
              <EyeOff className="h-4 w-4" />
              Turn Subtitles Off
            </button>
          </div>

          {/* Available Tracks */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold uppercase tracking-wider text-emerald-400/80">
                Available Tracks ({tracks.length})
              </span>
              {loading && <Loader2 className="h-3.5 w-3.5 animate-spin text-emerald-400" />}
            </div>

            {tracks.length === 0 && !loading ? (
              <div className="rounded border border-dashed border-emerald-500/20 p-4 text-center text-xs text-emerald-500/70">
                No subtitle tracks available for this media
              </div>
            ) : (
              <div className="space-y-1.5">
                {tracks.map((track) => {
                  const isActive = activeTrackIds.includes(track.track_id);
                  return (
                    <button
                      key={track.track_id}
                      type="button"
                      onClick={() => handleSelectTrack(track.track_id)}
                      className={`flex w-full items-center justify-between rounded border p-3 text-left transition-all ${
                        isActive
                          ? "border-emerald-400/70 bg-emerald-500/20 text-emerald-100 shadow-sm"
                          : "border-emerald-500/20 bg-emerald-500/5 text-emerald-300 hover:bg-emerald-500/10 hover:border-emerald-500/35"
                      }`}
                    >
                      <div className="flex items-center gap-2.5 truncate">
                        {isActive ? (
                          <Check className="h-4 w-4 shrink-0 text-emerald-300" />
                        ) : (
                          <div className="h-4 w-4 shrink-0 rounded-full border border-emerald-500/30" />
                        )}
                        <span className="truncate text-sm font-medium">{track.label || track.language}</span>
                      </div>

                      <div className="flex items-center gap-1.5 shrink-0 pl-2">
                        {track.source && (
                          <span className="rounded bg-emerald-950/80 border border-emerald-500/20 px-1.5 py-0.5 text-[10px] font-mono text-emerald-400/80 uppercase">
                            {track.source}
                          </span>
                        )}
                        <span className="rounded bg-emerald-500/20 px-1.5 py-0.5 text-[10px] font-mono font-bold text-emerald-200 uppercase">
                          {track.language}
                        </span>
                      </div>
                    </button>
                  );
                })}
              </div>
            )}
          </div>

          {/* Remote Subtitles Section */}
          {remoteSupported && (
            <div className="border-t border-emerald-500/20 pt-5 space-y-4">
              <div className="flex items-center gap-2">
                <Globe className="h-4 w-4 text-emerald-400" />
                <h3 className="text-xs font-semibold uppercase tracking-wider text-emerald-400/80">
                  {isYouTube ? "YouTube Remote Captions" : "Search External Subtitles"}
                </h3>
              </div>

              {remoteError && (
                <div className="flex items-center gap-2 rounded border border-red-500/40 bg-red-500/10 p-2.5 text-xs text-red-300">
                  <AlertCircle className="h-3.5 w-3.5 shrink-0 text-red-400" />
                  <span>{remoteError}</span>
                </div>
              )}

              {/* YouTube Tabbed Section */}
              {isYouTube && (
                <div className="space-y-3">
                  <div className="grid grid-cols-3 gap-1 rounded border border-emerald-500/20 bg-emerald-950/40 p-1 text-xs">
                    <button
                      type="button"
                      onClick={() => setYoutubeTab("manual")}
                      className={`rounded py-1.5 font-medium transition-all ${
                        youtubeTab === "manual"
                          ? "bg-emerald-500/30 text-emerald-100 font-semibold"
                          : "text-emerald-400/70 hover:text-emerald-200"
                      }`}
                    >
                      Creator / Manual
                    </button>
                    <button
                      type="button"
                      onClick={() => setYoutubeTab("autogenerated")}
                      className={`rounded py-1.5 font-medium transition-all ${
                        youtubeTab === "autogenerated"
                          ? "bg-emerald-500/30 text-emerald-100 font-semibold"
                          : "text-emerald-400/70 hover:text-emerald-200"
                      }`}
                    >
                      (autogenerated)
                    </button>
                    <button
                      type="button"
                      onClick={() => setYoutubeTab("translated")}
                      className={`rounded py-1.5 font-medium transition-all ${
                        youtubeTab === "translated"
                          ? "bg-emerald-500/30 text-emerald-100 font-semibold"
                          : "text-emerald-400/70 hover:text-emerald-200"
                      }`}
                    >
                      (translated)
                    </button>
                  </div>

                  {loadingRemote ? (
                    <div className="flex items-center justify-center gap-2 py-6 text-xs text-emerald-400/70">
                      <Loader2 className="h-4 w-4 animate-spin text-emerald-400" />
                      Loading YouTube captions...
                    </div>
                  ) : youtubeTracksForTab.length === 0 ? (
                    <div className="rounded border border-dashed border-emerald-500/20 p-4 text-center text-xs text-emerald-500/70">
                      No captions found for this category
                    </div>
                  ) : (
                    <div className="max-h-60 overflow-y-auto space-y-1 pr-1">
                      {youtubeTracksForTab.map((t, idx) => {
                        const isFetching = fetchingUrl === t.url;
                        return (
                          <button
                            key={`${t.url}-${idx}`}
                            type="button"
                            disabled={isFetching || Boolean(fetchingUrl)}
                            onClick={() => handleFetchRemote(t)}
                            className="flex w-full items-center justify-between rounded border border-emerald-500/15 bg-emerald-500/5 p-2.5 text-left text-xs text-emerald-300 hover:bg-emerald-500/15 hover:border-emerald-500/30 disabled:opacity-50 transition-all"
                          >
                            <span className="truncate pr-2">{t.label || t.language_name || t.language}</span>
                            <div className="flex items-center gap-2 shrink-0">
                              <span className="rounded bg-emerald-500/20 px-1.5 py-0.5 font-mono text-[10px] uppercase text-emerald-200">
                                {t.language}
                              </span>
                              {isFetching && <Loader2 className="h-3.5 w-3.5 animate-spin text-emerald-400" />}
                            </div>
                          </button>
                        );
                      })}
                    </div>
                  )}
                </div>
              )}

              {/* Local Media Search Section */}
              {isLocal && (
                <div className="space-y-3">
                  <form onSubmit={handleLocalSearch} className="flex gap-2">
                    <input
                      type="text"
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                      placeholder="Search subtitles (title or IMDb)..."
                      className="flex-1 rounded border border-emerald-500/30 bg-[#050807] px-3 py-1.5 text-xs text-emerald-200 placeholder-emerald-600 focus:border-emerald-400 focus:outline-none"
                    />
                    <button
                      type="submit"
                      disabled={loadingRemote}
                      className="flex items-center gap-1.5 rounded border border-emerald-500/40 bg-emerald-500/15 px-3 py-1.5 text-xs font-medium text-emerald-200 hover:bg-emerald-500/25 disabled:opacity-50 transition-colors"
                    >
                      {loadingRemote ? (
                        <Loader2 className="h-3.5 w-3.5 animate-spin" />
                      ) : (
                        <Search className="h-3.5 w-3.5" />
                      )}
                      Search
                    </button>
                  </form>

                  {loadingRemote ? (
                    <div className="flex items-center justify-center gap-2 py-6 text-xs text-emerald-400/70">
                      <Loader2 className="h-4 w-4 animate-spin text-emerald-400" />
                      Searching SubDL / OpenSubtitles...
                    </div>
                  ) : remoteSubtitles.length > 0 ? (
                    <div className="max-h-60 overflow-y-auto space-y-1.5 pr-1">
                      {remoteSubtitles.map((sub, idx) => {
                        const isFetching = fetchingUrl === sub.url;
                        return (
                          <button
                            key={`${sub.url}-${idx}`}
                            type="button"
                            disabled={isFetching || Boolean(fetchingUrl)}
                            onClick={() => handleFetchRemote(sub)}
                            className="flex w-full items-center justify-between rounded border border-emerald-500/20 bg-emerald-500/5 p-2.5 text-left text-xs text-emerald-300 hover:bg-emerald-500/15 hover:border-emerald-500/40 disabled:opacity-50 transition-all"
                          >
                            <div className="truncate pr-2">
                              <div className="font-medium text-emerald-200 truncate">{sub.label}</div>
                              {sub.release_name && (
                                <div className="text-[10px] text-emerald-500/70 truncate">{sub.release_name}</div>
                              )}
                            </div>
                            <div className="flex items-center gap-2 shrink-0">
                              <span className="rounded bg-emerald-500/20 px-1.5 py-0.5 font-mono text-[10px] uppercase text-emerald-200">
                                {sub.language}
                              </span>
                              {isFetching && <Loader2 className="h-3.5 w-3.5 animate-spin text-emerald-400" />}
                            </div>
                          </button>
                        );
                      })}
                    </div>
                  ) : null}
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default SubtitlesDrawer;
