# synchronization-map: section=media-routing; role=remote-subtitles; boundaries=core-service; doc=docs/SYNCHRONIZATION_MAP.md
"""Context-sensitive remote subtitle providers (YouTube yt-dlp & SubDL / OpenSubtitles fallback)."""

from __future__ import annotations

import gzip
import hashlib
import io
import json
import logging
import os
import re
import shutil
import subprocess
import urllib.parse
import urllib.request
import zipfile
from typing import Optional

from .opensubtitles import language3, srt_to_vtt, _request as opensubtitles_request

logger = logging.getLogger("castcast.subtitles_remote")

SUBTITLE_EXTENSIONS = {".vtt", ".srt", ".ass", ".ssa", ".sub"}

LANGUAGE_NAMES = {
    "eng": "English", "en": "English",
    "spa": "Spanish", "es": "Spanish",
    "fre": "French", "fra": "French", "fr": "French",
    "ger": "German", "deu": "German", "de": "German",
    "ita": "Italian", "it": "Italian",
    "jpn": "Japanese", "ja": "Japanese",
    "zho": "Chinese", "chi": "Chinese", "zh": "Chinese",
    "kor": "Korean", "ko": "Korean",
    "rus": "Russian", "ru": "Russian",
    "por": "Portuguese", "pt": "Portuguese",
    "hin": "Hindi", "hi": "Hindi",
    "ara": "Arabic", "ar": "Arabic",
    "pol": "Polish", "pl": "Polish",
    "nld": "Dutch", "dut": "Dutch", "nl": "Dutch",
    "swe": "Swedish", "sv": "Swedish",
    "nor": "Norwegian", "no": "Norwegian",
    "dan": "Danish", "da": "Danish",
    "fin": "Finnish", "fi": "Finnish",
    "ell": "Greek", "gre": "Greek", "el": "Greek",
    "tur": "Turkish", "tr": "Turkish",
    "heb": "Hebrew", "he": "Hebrew",
    "tha": "Thai", "th": "Thai",
    "vie": "Vietnamese", "vi": "Vietnamese",
    "ind": "Indonesian", "id": "Indonesian",
    "ces": "Czech", "cze": "Czech", "cs": "Czech",
    "hun": "Hungarian", "hu": "Hungarian",
    "ukr": "Ukrainian", "uk": "Ukrainian",
    "und": "Undetermined",
}


def _best_format_entry(formats: list[dict] | dict) -> Optional[dict]:
    if isinstance(formats, dict):
        formats = [formats]
    if not isinstance(formats, list) or not formats:
        return None

    # Filter out entries missing URL
    with_urls = [f for f in formats if isinstance(f, dict) and f.get("url")]
    if not with_urls:
        return None

    # Prefer WebVTT first
    for f in with_urls:
        if (f.get("ext") or "").lower() == "vtt":
            return f
    # Then SRT
    for f in with_urls:
        if (f.get("ext") or "").lower() == "srt":
            return f
    # Otherwise first available
    return with_urls[0]


def parse_youtube_subtitles(info_dict: dict) -> list[dict]:
    """Categorize yt-dlp tracks into Creator/Manual, autogenerated, and translated."""
    if not isinstance(info_dict, dict):
        return []

    tracks: list[dict] = []

    # 1. Manual / Creator subtitles
    raw_subs = info_dict.get("subtitles") or {}
    if isinstance(raw_subs, dict):
        for lang_code, formats in raw_subs.items():
            best = _best_format_entry(formats)
            if not best or not best.get("url"):
                continue

            base_lang = lang_code.split("-")[0].split("_")[0].lower()
            lang3 = language3(base_lang)
            lang_name = LANGUAGE_NAMES.get(lang3, LANGUAGE_NAMES.get(base_lang, LANGUAGE_NAMES.get(lang_code, lang_code.upper())))
            name = (best.get("name") or "").strip()
            display_name = name or lang_name
            url = best["url"]

            tracks.append({
                "language": lang3,
                "language_name": lang_name,
                "label": display_name,
                "type": "manual",
                "url": url,
                "download_url": url,
                "source": "youtube",
            })

    # 2. Automatic captions (autogenerated vs translated)
    raw_auto = info_dict.get("automatic_captions") or {}
    if isinstance(raw_auto, dict) and raw_auto:
        audio_lang = (
            info_dict.get("language")
            or info_dict.get("audio_language")
            or ""
        ).strip().lower()
        if not audio_lang:
            audio_lang = next(iter(raw_auto.keys()), "").strip().lower()

        audio_base = audio_lang.split("-")[0].split("_")[0] if audio_lang else ""
        audio_lang3 = language3(audio_base) if audio_base else ""

        for lang_code, formats in raw_auto.items():
            best = _best_format_entry(formats)
            if not best or not best.get("url"):
                continue

            base_lang = lang_code.split("-")[0].split("_")[0].lower()
            lang3 = language3(base_lang)
            lang_base = base_lang
            is_audio = bool(
                (audio_lang3 and lang3 == audio_lang3)
                or (audio_base and lang_base == audio_base)
            )

            lang_name = LANGUAGE_NAMES.get(lang3, LANGUAGE_NAMES.get(base_lang, LANGUAGE_NAMES.get(lang_code, lang_code.upper())))
            name = (best.get("name") or "").strip()
            display_name = name or lang_name
            url = best["url"]

            if is_audio:
                track_type = "autogenerated"
                label = f"{display_name} (autogenerated)"
            else:
                track_type = "translated"
                label = f"{display_name} (translated)"

            tracks.append({
                "language": lang3,
                "language_name": lang_name,
                "label": label,
                "type": track_type,
                "url": url,
                "download_url": url,
                "source": "youtube",
            })

    logger.debug(
        "DEBUG-ONLY: parsed %d YouTube subtitle tracks (%d manual, %d auto/translated)",
        len(tracks),
        sum(1 for t in tracks if t["type"] == "manual"),
        sum(1 for t in tracks if t["type"] != "manual"),
    )
    return tracks


class SubDLClient:
    """Client for SubDL subtitle search with automatic fallback to OpenSubtitles."""

    API_URL = "https://api.subdl.com/api/v1/subtitles"
    DOWNLOAD_BASE = "https://dl.subdl.com"

    def __init__(
        self,
        api_key: str = "",
        opensubtitles_api_key: str = "",
        opensubtitles_token: str = "",
    ):
        self.api_key = api_key or os.getenv("SUBDL_API_KEY", "")
        self.opensubtitles_api_key = opensubtitles_api_key or os.getenv("OPENSUBTITLES_API_KEY", "")
        self.opensubtitles_token = opensubtitles_token or os.getenv("OPENSUBTITLES_TOKEN", "")

    def search(
        self,
        imdb_id: str = "",
        query: str = "",
        languages: list[str] | None = None,
    ) -> list[dict]:
        """Search subtitles via SubDL API, falling back to OpenSubtitles if needed."""
        if not self.api_key:
            logger.debug("DEBUG-ONLY: SubDL api_key not set, skipping SubDL and falling back to OpenSubtitles")
            if self.opensubtitles_api_key and (imdb_id or query):
                return self._search_opensubtitles(imdb_id=imdb_id, query=query, languages=languages)
            return []

        results: list[dict] = []
        params: dict[str, str] = {}
        if self.api_key:
            params["api_key"] = self.api_key
        if imdb_id:
            params["imdb_id"] = imdb_id
        if query:
            params["film_name"] = query
        if languages:
            params["languages"] = ",".join(languages)

        url = f"{self.API_URL}?{urllib.parse.urlencode(params)}"
        logger.debug(
            "DEBUG-ONLY: querying SubDL API: url=%s imdb_id=%s query=%s languages=%s",
            url,
            imdb_id,
            query,
            languages,
        )

        try:
            req = urllib.request.Request(
                url,
                headers={
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) CastCast/1.0",
                    "Accept": "application/json",
                },
            )
            with urllib.request.urlopen(req, timeout=10) as resp:
                data = json.loads(resp.read().decode("utf-8", "replace") or "{}")

            if isinstance(data, dict) and data.get("status"):
                subs = data.get("subtitles") or []
                for sub in subs:
                    raw_url = sub.get("url") or ""
                    if not raw_url:
                        continue
                    if raw_url.startswith(("http://", "https://")):
                        dl_url = raw_url
                    else:
                        dl_url = f"{self.DOWNLOAD_BASE}/{raw_url.lstrip('/')}"

                    raw_lang = sub.get("language") or ""
                    lang3 = language3(raw_lang)
                    lang_name = LANGUAGE_NAMES.get(lang3, raw_lang or lang3.upper())
                    release_name = (sub.get("release_name") or sub.get("release") or "").strip()
                    label = f"{lang_name} ({release_name})" if release_name else lang_name

                    results.append({
                        "language": lang3,
                        "language_name": lang_name,
                        "label": label,
                        "url": dl_url,
                        "download_url": dl_url,
                        "type": "manual",
                        "source": "subdl",
                        "release_name": release_name,
                    })
                logger.debug("DEBUG-ONLY: SubDL returned %d subtitle tracks", len(results))
        except Exception as exc:
            logger.debug("DEBUG-ONLY: SubDL search request failed: %s", exc)

        # Fallback to OpenSubtitles if 0 results and credentials exist
        if not results and self.opensubtitles_api_key and (imdb_id or query):
            logger.debug("DEBUG-ONLY: SubDL returned 0 results, attempting OpenSubtitles fallback")
            results = self._search_opensubtitles(imdb_id=imdb_id, query=query, languages=languages)

        return results

    def _search_opensubtitles(
        self,
        imdb_id: str = "",
        query: str = "",
        languages: list[str] | None = None,
    ) -> list[dict]:
        results: list[dict] = []
        os_params: dict[str, str] = {}
        if imdb_id:
            clean_imdb = re.sub(r"[^0-9]", "", imdb_id)
            if clean_imdb:
                os_params["imdb_id"] = clean_imdb
        if query and "imdb_id" not in os_params:
            os_params["query"] = query
        if languages:
            os_params["languages"] = ",".join([language3(l) for l in languages])

        logger.debug("DEBUG-ONLY: querying OpenSubtitles API fallback with params=%s", os_params)
        try:
            resp_data = opensubtitles_request(
                f"/subtitles?{urllib.parse.urlencode(os_params)}",
                self.opensubtitles_api_key,
                token=self.opensubtitles_token,
            )
            data_list = resp_data.get("data") or []
            for item in data_list:
                attrs = item.get("attributes") or {}
                files = attrs.get("files") or []
                if not files:
                    continue
                file_id = files[0].get("file_id")
                if not file_id:
                    continue

                raw_lang = attrs.get("language") or ""
                lang3 = language3(raw_lang)
                lang_name = LANGUAGE_NAMES.get(lang3, raw_lang or lang3.upper())
                release_name = (attrs.get("release") or "").strip()
                label = f"{lang_name} ({release_name})" if release_name else lang_name

                os_url = f"opensubtitles:{file_id}"
                results.append({
                    "language": lang3,
                    "language_name": lang_name,
                    "label": label,
                    "url": os_url,
                    "download_url": os_url,
                    "type": "manual",
                    "source": "opensubtitles",
                    "release_name": release_name,
                })
            logger.debug("DEBUG-ONLY: OpenSubtitles fallback returned %d tracks", len(results))
        except Exception as exc:
            logger.debug("DEBUG-ONLY: OpenSubtitles fallback query failed: %s", exc)

        return results


def download_subtitle_to_vtt(
    url: str,
    work_dir: str,
    filename_hint: str = "",
    opensubtitles_api_key: str = "",
    opensubtitles_token: str = "",
) -> str:
    """Download remote subtitle archive or file, convert to WebVTT, and return local path."""
    if not url:
        raise ValueError("URL is required to download subtitle")

    os.makedirs(work_dir, exist_ok=True)
    stem = hashlib.sha1((url + filename_hint).encode("utf-8")).hexdigest()[:12]
    safe_hint = re.sub(r"[^a-zA-Z0-9_.-]", "_", filename_hint) if filename_hint else "remote"
    if safe_hint.lower().endswith(".vtt"):
        safe_hint = safe_hint[:-4]
    out_path = os.path.join(work_dir, f"{safe_hint}.{stem}.vtt")

    # 0. Check cache hit
    if os.path.exists(out_path) and os.path.getsize(out_path) > 0:
        logger.debug("DEBUG-ONLY: cache hit for remote subtitle %s -> %s", url, out_path)
        return os.path.abspath(out_path)

    logger.debug("DEBUG-ONLY: downloading subtitle from %s -> %s", url, out_path)

    # 1. Fetch raw payload
    payload: bytes
    url_path = urllib.parse.urlsplit(url).path
    actual_filename = os.path.basename(url_path) if url_path else ""
    actual_ext = os.path.splitext(actual_filename)[1].lower() if actual_filename else ""

    if os.path.isfile(url):
        with open(url, "rb") as f:
            payload = f.read()
    elif url.startswith("opensubtitles:"):
        file_id = url.split(":", 1)[1]
        api_key = opensubtitles_api_key or os.getenv("OPENSUBTITLES_API_KEY", "")
        token = opensubtitles_token or os.getenv("OPENSUBTITLES_TOKEN", "")
        if not api_key:
            raise RuntimeError("OpenSubtitles API key is required to download OpenSubtitles track")
        dl = opensubtitles_request(
            "/download",
            api_key,
            token=token,
            data={"file_id": int(file_id), "sub_format": "webvtt"},
        )
        dl_link = dl.get("link")
        if not dl_link:
            raise RuntimeError("OpenSubtitles download response did not contain link")
        actual_filename = dl.get("file_name") or actual_filename
        actual_ext = os.path.splitext(actual_filename)[1].lower()
        req = urllib.request.Request(
            dl_link,
            headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) CastCast/1.0"},
        )
        with urllib.request.urlopen(req, timeout=30) as res:
            payload = res.read()
    else:
        req = urllib.request.Request(
            url,
            headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) CastCast/1.0"},
        )
        with urllib.request.urlopen(req, timeout=30) as res:
            payload = res.read()

    if not payload:
        raise RuntimeError(f"Downloaded 0 bytes from {url}")

    # 2. Decompress if gzip
    if actual_ext == ".gz" or actual_filename.lower().endswith(".gz") or payload.startswith(b"\x1f\x8b"):
        logger.debug("DEBUG-ONLY: decompressing gzip subtitle payload")
        payload = gzip.decompress(payload)
        if actual_filename.lower().endswith(".gz"):
            actual_filename = actual_filename[:-3]
            actual_ext = os.path.splitext(actual_filename)[1].lower()

    # 3. Extract if zip
    if actual_ext == ".zip" or actual_filename.lower().endswith(".zip") or payload.startswith(b"PK\x03\x04") or zipfile.is_zipfile(io.BytesIO(payload)):
        logger.debug("DEBUG-ONLY: extracting zip subtitle archive")
        with zipfile.ZipFile(io.BytesIO(payload)) as zf:
            candidates = [
                n for n in zf.namelist()
                if not n.startswith("__MACOSX") and os.path.splitext(n)[1].lower() in SUBTITLE_EXTENSIONS
            ]
            if not candidates:
                candidates = [n for n in zf.namelist() if not n.endswith("/") and not n.startswith("__MACOSX")]
            if not candidates:
                raise RuntimeError("Zip archive contains no subtitle files")

            vtt_candidates = [n for n in candidates if n.lower().endswith(".vtt")]
            srt_candidates = [n for n in candidates if n.lower().endswith(".srt")]
            chosen = vtt_candidates[0] if vtt_candidates else (srt_candidates[0] if srt_candidates else candidates[0])
            payload = zf.read(chosen)
            actual_filename = chosen
            actual_ext = os.path.splitext(chosen)[1].lower()

    # 4. Convert to WebVTT
    # Decode text
    try:
        text = payload.decode("utf-8")
    except UnicodeDecodeError:
        try:
            text = payload.decode("latin-1")
        except Exception:
            text = payload.decode("utf-8", errors="replace")

    normalized_stripped = text.lstrip("\ufeff\r\n ")
    is_vtt = normalized_stripped.startswith("WEBVTT")
    is_srt = (
        actual_ext == ".srt"
        or bool(re.search(r"\d\d:\d\d:\d\d,\d\d\d", normalized_stripped))
        or bool(re.search(r"^\d+\s*[\r\n]+\d\d:\d\d:\d\d", normalized_stripped))
    )

    if is_vtt:
        vtt_output = text
    elif is_srt:
        # Transform SRT to WebVTT (converts comma timestamps to period timestamps)
        vtt_output = srt_to_vtt(text)
    else:
        # Check if ffmpeg is available for other formats (.ass, .ssa, .sub)
        ffmpeg_bin = shutil.which("ffmpeg")
        if ffmpeg_bin:
            temp_in = os.path.join(work_dir, f"temp_{stem}{actual_ext or '.sub'}")
            try:
                with open(temp_in, "wb") as f:
                    f.write(payload)
                cmd = [ffmpeg_bin, "-hide_banner", "-y", "-i", temp_in, "-f", "webvtt", out_path]
                logger.debug("DEBUG-ONLY: converting subtitle with ffmpeg: %s", " ".join(cmd))
                proc = subprocess.run(cmd, capture_output=True, timeout=60, check=False)
                if proc.returncode == 0 and os.path.exists(out_path) and os.path.getsize(out_path) > 0:
                    return os.path.abspath(out_path)
                else:
                    if os.path.exists(out_path):
                        try:
                            os.unlink(out_path)
                        except OSError:
                            pass
            except Exception as exc:
                if os.path.exists(out_path):
                    try:
                        os.unlink(out_path)
                    except OSError:
                        pass
                logger.debug("DEBUG-ONLY: ffmpeg conversion failed or timed out: %s", exc)
            finally:
                if os.path.exists(temp_in):
                    try:
                        os.unlink(temp_in)
                    except OSError:
                        pass

        # Fallback to pure-Python srt_to_vtt
        vtt_output = srt_to_vtt(text)

    # Write output WebVTT file
    try:
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(vtt_output)
        if os.path.getsize(out_path) == 0:
            raise RuntimeError("Generated WebVTT file is 0 bytes")
    except Exception as exc:
        if os.path.exists(out_path):
            try:
                os.unlink(out_path)
            except OSError:
                pass
        raise RuntimeError(f"Failed to write WebVTT file: {exc}") from exc

    logger.debug("DEBUG-ONLY: successfully wrote WebVTT subtitle: %s", out_path)
    return os.path.abspath(out_path)
